### 챌린지 이미지 인증 요청 테스트 (FastAPI)
POST http://localhost:8000/ai/image/Verification
Content-Type: application/json

{
  "imageUrl": "https://storage.cloud.google.com/leafresh-images/example2.png",
  "memberId": 101,
  "challengeId": 123,
  "date": "2025-05-02",
  "challengeName": "제로웨이스트 챌린지"
}

